apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jupyterhub
  name: jupyterhub
  namespace: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jupyterhub
    spec:
      serviceAccountName: default
      containers:
      - image: shryu1/jupyter:5
        name: jupyter
        command: ["jupyterhub", "-f", "/opt/jupyter/jupyterhub_config.py"]
        ports:
        - containerPort: 8000
        - containerPort: 8081
        volumeMounts:
        - mountPath: "/opt/jupyter"
          name: jupyterhub-pv-storage
        resources: {}
      volumes:
      - name: jupyterhub-pv-storage
        persistentVolumeClaim:
          claimName: jupyterhub-pv-claim
status: {}
