apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jupyterhub
  name: jupyterhub-svc
  namespace: jupyterhub
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    name: port-80
  - port: 8081
    protocol: TCP
    targetPort: 8081
    name: port-8081
  - port: 8888
    protocol: TCP
    targetPort: 8888
    name: port-8888
  selector:
    app: jupyterhub
  type: NodePort
status:
  loadBalancer: {}
