apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-pv-claim
  namespace: jupyterhub
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
