kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jupyterhub-pod-creator-binding
  namespace: jupyterhub
subjects:
- kind: ServiceAccount
  name: default
  namespace: jupyterhub
roleRef:
  kind: Role
  name: jupyterhub-pod-creator
  apiGroup: rbac.authorization.k8s.io
