kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: jupyterhub
  name: jupyterhub-pod-creator
rules:
- apiGroups: [""]
  resources: ["pods", "events"]
  verbs: ["create", "delete", "get", "list", "watch"]
